### ISSUE TITLE
Block Kit JSON to React Components?

### ISSUE THREAD

**Issue by scott-wojan** [yhatt/jsx-slack#189]
Hello,

I need to do the opposite of this... convert the Block Kit JSON to React components.  Is that possible?

**Comment by yhatt** [comment]
No, we are only supporting "JSX to JSON". An opposite conversion is not planned for now, but it may be helpful when transforming exist Slack app into using jsx-slack.

> NOTE: jsx-slack is [not based on React](https://github.com/speee/jsx-slack#is-this-working-based-on-react).
