### ISSUE TITLE
Using inside of next.js

### ISSUE THREAD

**Issue by mwildehahn** [yhatt/jsx-slack#212]
👋 I'm looking at using this inside of next.js and I think I'm running into an issue with the tsconfig options.

Next.js forces:

```
    "jsx": "preserve",
```

So I don't think the jsx transformation is working properly. Have you tried this before?

**Comment by yhatt** [comment]
Forcing `"jsx": "preserve"` means that Next.js transpiles React JSX through Babel. So you still can use [comment pragma for Babel](https://github.com/speee/jsx-slack/blob/master/docs/how-to-setup-jsx-transpiler.md#comment-pragma) in JSX files that are splitted for jsx-slack.

```javascript
/** @jsx JSXSlack.h */
/** @jsxFragment JSXSlack.Fragment */
import { JSXSlack, Blocks } from '@speee-js/jsx-slack'
```

The recent Next.js using automatic runtime, [Next.js 9.5.3+](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#nextjs), may not able to use these classic pragmas. However, `/** @jsxImportSource @speee-js/jsx-slack */` comment pragma for automatic runtime may throw type error by TypeScript.

When you met the error `pragma and pragmaFrag cannot be set when runtime is automatic.` while building Next app, try adding `/** @jsxRuntime classic */` pragma to force classic runtime in JSX file for jsx-slack.

```javascript
/** @jsxRuntime classic */
/** @jsx JSXSlack.h */
/** @jsxFragment JSXSlack.Fragment */
import { JSXSlack, Blocks } from '@speee-js/jsx-slack'
```

**Comment by yhatt** [comment]
UPDATE: In the recent Next.js 9.5.3+, just use this magic comment:

```javascript
/** @jsxImportSource jsx-slack */
import {} from 'jsx-slack'
```

https://github.com/yhatt/jsx-slack/blob/master/docs/how-to-setup-jsx-transpiler.md#comment-pragma-2
