### ISSUE TITLE
multi select no longer required by default

### ISSUE THREAD

**Issue by smoneta** [yhatt/jsx-slack#237]
sample:
```
<Modal title="My first modal" close="Cancel">
  <Section id="multiSelectSample">
    <b>Select one or more</b>
    <Select placeholder="Click here to select" actionId="multiSelectSample" multiple>
      <Option>OPTION1</Option>
      <Option>OPTION2</Option>    
    </Select>
  </Section>
</Modal>
```

The code above use to complain if I try to submit without any selection, now that changed.. something changed? do I need to add 'required' somewhere?

**Comment by smoneta** [comment]
Looks like is an issue from BLOCK KIT, the [documentation](            
) say is required but the JSON sample fails ... so this needs to be reported to slack.... I will be closing this

**Comment by yhatt** [comment]
`required` is available only in the input block like this:

```jsx
<Modal title="My first modal" close="Cancel">
  <Input label="Select one or more" id="multiSelectSample" required>
    <Select placeholder="Click here to select" actionId="multiSelectSample" multiple>
      <Option>OPTION1</Option>
      <Option>OPTION2</Option>    
    </Select>
  </Input>
</Modal>
```

or:

```jsx
<Modal title="My first modal" close="Cancel">
  <Select label="Select one or more" id="multiSelectSample" required placeholder="Click here to select" actionId="multiSelectSample" multiple>
    <Option>OPTION1</Option>
    <Option>OPTION2</Option>    
  </Select>
</Modal>
```

Appearance of both are exactly same but there is a difference how to treat an input value. [The value of multi-select in `section` block can be handled in `block_actions` payload, and in `input` block can be in `view_submission` payload.](https://api.slack.com/interactivity/handling#payloads)

You have to use the input block if you want to leave `required` validation to Slack. If not, you have to update the state of modal manually within `block_actions` payload.

**Comment by yhatt** [comment]
See also: #222
