### ISSUE TITLE
How to mention a user?

### ISSUE THREAD

**Issue by smoneta** [yhatt/jsx-slack#240]
Hi, I need to mention a user using the format <@ABC123> which work on blockit but I cant get it to work on jsx... may I ask how it can be done?

block kit sample:
```
{
  "type": "section",
  "text": {
    "type": "mrkdwn",
    "text": "Approvers:\nRelease Management Team: Approved by <@WJNQ0AL9L>"
    "verbatim": true
  }
},
```
Thanks!

**Comment by yhatt** [comment]
See https://github.com/yhatt/jsx-slack/blob/main/docs/html-like-formatting.md#mention-to-user-and-user-group.

**Comment by smoneta** [comment]
THANKS!

**Comment by leoyli-headsup** [comment]
@yhatt, Would you consider to add alias like `<Link>` or `<Mention>` component? As they are much semantically readable.

**Comment by yhatt** [comment]
@leoyli-headsup jsx-slack components are basically based on Block Kit and I'm not thinking to add the alias component for mrkdwn syntaxes. But if you want, it's very easy to define aliases by user side as same as React.

```jsx
const Link = ({ children, href }) => <a href={href}>{children}</a>
const Mention = ({ id }) => <a href={`@${id}`} />

console.log(
  <Blocks>
    <Section>
      <Mention id="U0123456789" /> <Link href="https://example.com">Link</Link>
    </Section>
  </Blocks>
)
```

```javascript
[
  {
    type: 'section',
    text: {
      type: 'mrkdwn',
      text: '<@U0123456789> <https://example.com|Link>',
      verbatim: true
    }
  }
]
```

**Comment by leoyli-headsup** [comment]
@yhatt, thanks for a reply. I know I can do this, I was more on suggesting to make more intuitive and better DX. As these are very Slack specific thing. But thanks for an example.

**Comment by deepansh946** [comment]
How can we mention user using usernames?

**Comment by yhatt** [comment]
@deepansh946 See https://api.slack.com/changelog/2017-09-the-one-about-usernames. Generally your Slack app should [map the username to user ID](https://api.slack.com/changelog/2017-09-the-one-about-usernames#mapping).

**Comment by deepansh946** [comment]
@yhatt i have tried using user names but its not mentioning it, did with userId it mentioned it

**Comment by yhatt** [comment]
@deepansh946 Did you read the Slack's article I've shared? Slack has phased out mention through user names, and now you can no longer mention without user ID. You should always use user ID to mention through Slack apps.
