### ISSUE TITLE
Add support for Options's description

### ISSUE THREAD

**Issue by brunano21** [yhatt/jsx-slack#284]
As per the title, I'd like to have the ability to set a [description](https://api.slack.com/reference/block-kit/composition-objects#option) for the Option object.

**Comment by yhatt** [comment]
For providing HTML-like experience, jsx-slack has provided components based on context. It means `<Option>` is for `<Select>` and similar interactive components, that `description` are not used in them.

To generate Option object with `description`, try using `<Checkbox>` or `<RadioButton>` instead.

```jsx
import { Checkbox } from 'jsx-slack'

console.log(
  <Checkbox value="value" description="description">text</Checkbox>
)
```

```json
{
  "text": {
    "type": "mrkdwn",
    "text": "text",
    "verbatim": true
  },
  "description": {
    "type": "mrkdwn",
    "text": "description",
    "verbatim": true
  },
  "value": "value"
}
```

[See this example on REPL...](https://jsx-slack.netlify.app/#jsx:eJyzcc5ITc5Oyq9QKEvMKU21VQJTSgopqcXJRZkFJZn5ebZKSBwlu5LUihIbfZg2OwASkBf7)

**Comment by yhatt** [comment]
Oh, it's first time to know that select components allow description field in option object.

![slack](https://user-images.githubusercontent.com/3993388/205717415-24d2eb41-2f90-499e-8b25-5c1fb2c9959c.png)
