### ISSUE TITLE
Convert html string to JSXSlack elements

### ISSUE THREAD

**Issue by KulovacNedim** [yhatt/jsx-slack#306]
Hi guys. We've been using this library for a long time already and it's great. However, I did not notice if there is support/functionality for converting HTML strings to JSX elements.

I have an HTML string saved in the database. Example: `<div><p>Some <b>text</b> here</p></div>`. 
I would like to convert it to HTML or JSX, so I can for example wrap it into `<Section>` and take advantage of HTML-like formatting, and compose Slack blocks from it.

How can this be achieved? I made some progress with parsing HTML string to dom (with jsdom library), but it became pretty messy with nested elements. I'm stuck and can't figure it any further.

Is there any reliable way to achieve this? Thanks in advance.

**Comment by yhatt** [comment]
Duplicated: #163 

```javascript
// example.js
import { jsxslack } from 'jsx-slack';

const html = "<p>Some <b>text</b> here</p>";
console.log(jsxslack([`<Mrkdwn>${html}</Mrkdwn>`]))
/*
{
  "type": "mrkdwn",
  "text": "Some *text* here"
}
*/
```

**Comment by KulovacNedim** [comment]
Hey @yhatt - thanks for such a fast reply. Your example works. I'm not sure if I'm doing something wrong, but it does not work for my use case. 
Have a look at this HTML string (in reality it's a single line, I formated it here a bit for the sake of readability):
```
<div>
    <p>Use 5 a password manager. ...
    <p></p>
    <ol>
	<li>Dont write or print passwords on ....</li>
	<li>password on the backside of....</li>
	<li>Use long, random, but memorable passwords...</li>
	<li>Dont use the same password everywhere. </li>
	<ul>
		<li>11111<li>
		<li>2222<li>
	<ul>
	<li>Where possible, .....</li>
    </ol>
</div>
```
If I assign this string to `html` variable in your example, I get this output: `[ 'li', null, [Object: null prototype] {} ]`

If I pass ``<Mrkdwn>${html}</Mrkdwn>`` to the `convert` function (thanks for the hint btw), I get the same result - it works for your markup, and it does not work for mine.

Any idea why my HTML string does not work in your example?

\\\
Also, besides the HTML string, I also have a text in markdown format saved. I managed to use that with the `<Markdown>` component. The reason why I prefer HTML-like formatting is because lists and nested lists render better with HTML markup.

**Comment by yhatt** [comment]
`<div>` element is not supported HTML element by jsx-slack. Before passing string of HTML to `jsxslack` template literal tag, you might need to sanitize not supported elements. (e.g. replace to `<section>` or `<Fragment>`, through `String.replace()`)

Type definition of supported HTML tags is available in [https://github.com/yhatt/jsx-slack/blob/b9b6e1236e03321539996dd217f0664d600c5516/src/jsx.ts#L283](https://github.com/yhatt/jsx-slack/blob/b9b6e1236e03321539996dd217f0664d600c5516/src/jsx.ts#L283?).

**Comment by KulovacNedim** [comment]
Okay, so I replaced unsupported tags and got the same output. have a look at this:


```
const htmlString = `<section><p>This is a paragraph</p><ol><li>item 1</li><li>Item 2</li><ol></section>`
const result = jsxslack([`<Mrkdwn>${html2}</Mrkdwn>`])

console.log(result)
console.log("----------")

const result2 = JSXSlack(<Section><Mrkdwn>${html2}</Mrkdwn></Section>)

console.log(result2)

```

Output:
```
['section', null, [Object: null prototype] {}, [Object: null prototype] {} ]
----------
{
  type: 'section',
  text: {
    type: 'mrkdwn',
    text: '$&lt;section&gt;&lt;p&gt;This is a paragraph&lt;/p&gt;&lt;ol&gt;&lt;li&gt;item 1&lt;/li&gt;&lt;li&gt;Item 2&lt;/li&gt;&lt;ol&gt;&lt;/section&gt;'
  }
}
```

Sorry for bothering you with this and thanks for your effort to help.

**Comment by KulovacNedim** [comment]
Hey man, I got this working! removing the `<section>` element and passing the rest of the string works fine. I think I got what I was doing wrong. 

Thanks a lot for your help!

**Comment by yhatt** [comment]
I’m relieved to hear that :) 

The following example is a revised version of the previous code that you've been provided.

```javascript
import { jsxslack, JSXSlack, Section } from 'jsx-slack';

const htmlString = `<p>This is a paragraph</p><ol><li>item 1</li><li>Item 2</li></ol>`;
const result = jsxslack([`<Mrkdwn>${htmlString}</Mrkdwn>`]); // result is Slack's mrkdwn object

console.log(result);
console.log('----------');

// Pass mrkdwn object as a child of the section block
const result2 = JSXSlack(<Section>{result}</Section>);

console.log(result2);
```

**Comment by KulovacNedim** [comment]
Thanks a lot for your help! It works like a charm!
