### ISSUE TITLE
Passing a string variable to jsxslack (inside of, or instead of, a template literal)

### ISSUE THREAD

**Issue by crustyratfink** [yhatt/jsx-slack#307]
Hi,

Your library would be great for a project I'm working on, but I seem to be running into a fukuzatsu na problem with passing a dynamically generated string in (e.g., from rendering markdown to JSX):

If I do:
```
    const stuff = `<Blocks><Section><b>Hi.</b></Section><Divider /></Blocks>`
    parsed = jsxslack`<Blocks><Section><b>Hi.</b></Section><Divider /></Blocks>`;
    console.log("Parsed 1: ", parsed);
    parsed = jsxslack`${stuff}`;
    console.log("Parsed 2: ", parsed);
```

I get:
```
Parsed 1:  [
  {
    type: 'section',
    text: { type: 'mrkdwn', text: '*Hi.*', verbatim: true }
  },
  { type: 'divider' }
]
Parsed 2:  [String: '<Blocks><Section><b>Hi.</b></Section><Divider /></Blocks>']
```

It seems no matter what I do, I can't pass in a string representing JSX as a variable, which means I can't generate the string and then pass it in.  For what it's worth, I'm using Markdownit to create the string from Markdown.

Any suggestions?

**Comment by yhatt** [comment]
Similar:

- #163
- #306

In both of JSX and template literal tags, the string representation of JSX elements in braces is recognized as just a string, not JSX. For example, `` jsxslack`${stuff}` `` is almost equivalent to JSX `<>{stuff}</>`. 

You can pass the JSX representation as a variable, by using  the `jsxslack` template literal tag as the function. This is exactly how our REPL demo converts the string to actual JSX.

https://github.com/yhatt/jsx-slack/blob/b9b6e1236e03321539996dd217f0664d600c5516/demo/js/convert.js#L10

Note that the string is wrapped in an array. Once you understand [how the template literal tag works](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates), you may understand why this works like magic :)
