### ISSUE TITLE
eslint issue

### ISSUE THREAD

**Issue by SeungyeopShin** [yhatt/jsx-slack#311]
I succeeded with your suggestion https://github.com/yhatt/jsx-slack/issues/310#issuecomment-1882976826

But eslint issue is happend.

If `jsxslack` used with templatestring is OK, but in case of it used with array paramter, eslint cache error.
Is there any workaround these errors without eslint comment.

**Normal Case**
```javascript
  const slackBlockKit = jsxslack`<Blocks>
      <Section>
        ${htmlString}
      </Section>
    </Blocks>`

// In this case, jsx is escaped.
```
**Error Case**
```javascript
  const slackBlockKit = jsxslack([
    `<Blocks>
      <Section>
        ${htmlString}
      </Section>
    </Blocks>`
  ] as any)

// output
  5:30  error  Unsafe call of an `any` typed value            @typescript-eslint/no-unsafe-call
  7:9   error  Unsafe assignment of an `any` value            @typescript-eslint/no-unsafe-assignment
  7:25  error  Unsafe call of an `any` typed value            @typescript-eslint/no-unsafe-call
```

**Comment by yhatt** [comment]
```typescript
const slackBlockKit = jsxslack([
  `<Blocks>
    <Section>
      ${htmlString}
    </Section>
  </Blocks>`
] as unknown as TemplateStringsArray)
```

`TemplateStringsArray`, the built-in type currently used by jsx-slack, is having a bit diffrent shape of type from the required type by `jsxslack` template literal tag. I will fix that in the next major version to eliminate the need for type casting.

**Comment by SeungyeopShin** [comment]
I tried your suggeston but also error deteced by eslint.
```
error  Unsafe assignment of an `any` value  @typescript-eslint/no-unsafe-assignment
```
And I'm looking forward to patch for this issue
Thanks for your helping. 👍

**Comment by yhatt** [comment]
The return type of `jsxslack(...)` is always any. If your TS project does never allow `any` type, probably you should explicitly annotate `slackBlockKit` with the appropriate type.

```typescript
import type { Block } from '@slack/types'

const slackBlockKit: Block[] = jsxslack`...`
```

That seems more like related to [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) than jsx-slack, so you may get deeper insight by asking at the typescript-eslint community.
